use std::collections::HashSet;

use crate::parser::Parser;

mod parser;

fn main() {
    let iterations = 1;
    let mut parser = Parser::new();

    // let target: Vec<usize> = "
    //     'Cause baby, now we got bad blood You know it used to be mad love So take a look what you've done 'Cause baby, now we got bad blood, hey Now we got problems And I don't think we can solve 'em You made a really deep cut And baby, now we got bad blood, hey  Did you have to do this? I was thinking that you could be trusted Did you have to ruin What was shiny? Now it's all rusted  Did you have to hit me Where I'm weak? Baby, I couldn't breathe and Rub it in so deep Salt in the wound like you're laughing right at me  Oh, it's so sad to Think about the good times You and I  'Cause baby, now we got bad blood You know it used to be mad love So take a look what you've done 'Cause baby, now we got bad blood, hey Now we got problems And I don't think we can solve 'em You made a really deep cut And baby, now we got bad blood, hey  Did you think we'd be fine? Still got scars on my back from your knife So, don't think it's in the past These kinds of wounds they last, and they last  Now, did you think it all through? All these things will catch up to you And time can heal but this won't So if you're coming my way Just don't  Oh, it's so sad to Think about the good times You and I  'Cause baby, now we got bad blood You know it used to be mad love So take a look what you've done 'Cause baby, now we got bad blood, hey Now we got problems And I don't think we can solve 'em You made a really deep cut And baby, now we got bad blood, hey  Band-Aids don't fix bullet holes You say sorry just for show If you live like that, you live with ghosts (Ghosts) Band-Aids don't fix bullet holes You say sorry just for show If you live like that, you live with ghosts, mmm If you love like that Blood runs cold  'Cause baby, now we got bad blood You know it used to be mad love So take a look what you've done 'Cause baby, now we got bad blood, hey (Bad blood, bad blood) Now we got problems And I don't think we can solve 'em (Think we can solve 'em) You made a really deep cut And baby, now we got bad blood  And baby, now we got bad blood ('Cause now we got bad blood) You know it used to be mad love So take a look what you've done (Look what you've done) 'Cause baby, now we got bad blood, hey Now we got problems And I don't think we can solve 'em You made a really deep cut And baby, now we got bad blood, hey
    //     I walked through the door with you The air was cold But something 'bout it felt like home somehow and I Left my scarf there at your sister's house And you've still got it in your drawer even now  Oh, your sweet disposition And my wide-eyed gaze We're singing in the car, getting lost upstate Autumn leaves falling down like pieces into place And I can picture it after all these days And I know it's long gone and that magic's not here no more And I might be okay but I'm not fine at all, oh-oh-oh  'Cause there we are again on that Little town street You almost ran the red 'cause you were Looking over at me Wind in my hair, I was there I remember it all too well  Photo album on the counter Your cheeks were turning red You used to be a little kid with glasses in a twin-sized bed And your mother's telling stories 'bout you on the tee ball team You taught me about your past, thinking your future was me And I know it's long gone and there was nothing else I could do And I forget about you long enough to forget why I needed to  'Cause there we are again in the middle of the night We're dancing round the kitchen in the refrigerator light Down the stairs, I was there I remember it all too well, yeah  And maybe we got lost in translation Maybe I asked for too much But maybe this thing was a masterpiece Till you tore it all up Running scared, I was there I remember it all too well  And you call me up again Just to break me like a promise So casually cruel in the name of being honest I'm a crumpled up piece of paper lying here 'Cause I remember it all, all, all too well  Time won't fly, it's like I'm paralyzed by it I'd like to be my old self again but I'm still trying to find it After plaid shirt days and nights when you made me your own Now you mail back my things and I walk home alone But you keep my old scarf from that very first week 'Cause it reminds you of innocence and it smells like me You can't get rid of it 'Cause you remember it all too well  'Cause there we are again when I loved you so Back before you lost the one real thing you've ever known It was rare, I was there, I remember it all too well Wind in my hair, you were there, you remember it all Down the stairs, you were there, you remember it all It was rare, I was there, I remember it all too well
    //     We were both young when I first saw you I close my eyes and the flashback starts: I\'m standing there On a balcony in summer air  See the lights, see the party, the ball gowns See you make your way through the crowd And say, \"Hello.\" Little did I know  That you were Romeo, you were throwing pebbles And my daddy said, \"Stay away from Juliet.\" And I was crying on the staircase Begging you, \"Please don\'t go.\" And I said  \"Romeo, take me somewhere we can be alone I\'ll be waiting. All there\'s left to do is run You\'ll be the prince and I\'ll be the princess It\'s a love story. Baby, just say \'Yes\'.\"  So, I sneak out to the garden to see you We keep quiet \'cause we\'re dead if they knew So, close your eyes Escape this town for a little while Oh, oh  \'Cause you were Romeo. I was a scarlet letter And my daddy said, \"Stay away from Juliet.\" But you were everything to me I was begging you, \"Please don\'t go!\" And I said  \"Romeo, take me somewhere we can be alone I\'ll be waiting. All there\'s left to do is run You\'ll be the prince and I\'ll be the princess It\'s a love story. Baby, just say \'Yes\'  Romeo, save me. They\'re tryna tell me how to feel This love is difficult but it\'s real Don\'t be afraid. We\'ll make it out of this mess It\'s a love story. Baby, just say \'Yes\'.\"  Oh, oh, oh  I got tired of waiting Wondering if you were ever coming around My faith in you was fading When I met you on the outskirts of town And I said  \"Romeo, save me. I\'ve been feeling so alone I keep waiting for you, but you never come Is this in my head? I don\'t know what to think.\" He knelt to the ground and pulled out a ring and said  \"Marry me, Juliet. You\'ll never have to be alone I love you, and that\'s all I really know I talked to your dad. Go pick out a white dress It\'s a love story. Baby, just say \'Yes\'.\"  Oh, oh, oh, oh, oh, oh  \'Cause we were both young when I first saw you
    //     Drowning in the Blue Nile\nHe sent me \"Downtown Lights\"\nI hadn\'t heard it in a while\nMy boredom\'s bone-deep\nThis cage was once just fine\nAm I allowed to cry?\n\nI dream of cracking locks\nThrowing my life to the wolves or the ocean rocks\nCrashing into him tonight, he\'s a paradox\nI\'m seeing visions, am I bad?\nOr mad? Or wise?\n\nWhat if he\'s written \"mine\" on my upper thigh only in my mind?\nOne slip and falling back into the hedge maze\nOh, what a way to die\nI keep recalling things we never did\nMessy top lip kiss, how I long for our trysts\nWithout ever touching his skin\nHow can I be guilty as sin?\n\nI keep these longings locked\nIn lowercase, inside a vault\nSomeone told me there\'s no such thing as bad thoughts\nOnly your actions talk\n\nThese fatal fantasies giving way to labored breath\nTaking all of me, we\'ve already done it in my head\nIf it\'s make-believe\nWhy does it feel like a vow we\'ll both uphold somehow?\n\nWhat if he\'s written \"mine\" on my upper thigh only in my mind?\nOne slip and falling back into the hedge maze\nOh, what a way to die\nMy bedsheets are ablaze, I\'ve screamed his name\nBuilding up like waves crashing over my grave\nWithout ever touching his skin\nHow can I be guilty as sin?\n\nWhat if I roll the stone away?\nThey\'re gonna crucify me anyway\nWhat if the way you hold me is actually what\'s holy?\nIf long-suffering propriety is what they want from me\nThey don\'t know how you\'ve haunted me so stunningly\nI choose you and me religiously\n\nWhat if he\'s written \"mine\" on my upper thigh only in my mind?\nOne slip and falling back into the hedge maze\nOh, what a way to die\nI keep recalling things we never did\nMessy top lip kiss, how I long for our trysts\nWithout ever touching his skin\nHow can I be guilty as sin?\n\nHe sent me \"Downtown Lights\"\nI hadn\'t heard it in a while\nAm I allowed to cry?
    //     Who\'s gonna stop us from waltzing back into rekindled flames\nIf we know the steps anyway?\nWe embroidered the memories of the time I was away\nStitching, \"We were just kids, babe\"\nI said, \"I don\'t mind, it takes time\"\nI thought I was better safe than starry-eyed\nI felt aglow like this\nNever before and never since\n\nIf you know it in one glimpse, it\'s legendary\nYou and I go from one kiss to getting married\nStill alive, killing time at the cemetery\nNever quite buried\nIn your suit and tie, in the nick of time\nYou lowdown boy, you standup guy, you\nHoly Ghost, you told me I\'m\nThe love of your life\n\nYou said I\'m the love of your life\nAbout a million times\n\nWho\'s gonna tell me the truth, when you blew in with the winds of fate\nAnd told me I reformed you?\nWhen your Impressionist paintings of Heaven turned out to be fakes\nWell, you took me to hell too\nAnd all at once, the ink bleeds\nA conman sells a fool a get-love-quick scheme\nBut I felt a hole like this\nNever before and ever since\n\nIf you know it in one glimpse, it\'s legendary\nWhat we thought was for all time was momentary\nStill alive, killing time at the cemetery\nNever quite buried\nYou cinephile in black and white\nAll those plot twists and dynamite\nMr. Steal Your Girl, then make her cry\nYou said I\'m the love of your life\n\nYou shit-talked me under the table, talking rings and talking cradles\nI wish I could un-recall how we almost had it all\nDancing phantoms on the terrace, are they second-hand embarrassed\nThat I can\'t get out of bed \'cause something counterfeit\'s dead?\nIt was legendary\nIt was momentary\nIt was unnecessary, should\'ve let it stay buried\n\nOh, what a valiant roar\nWhat a bland goodbye\nThe coward claimed he was a lion\nI\'m combing through the braids of lies\n\"I\'ll never leave\"\n\"Never mind\"\nOur field of dreams, engulfed in fire\nYour arson\'s match, your somber eyes\nAnd I\'ll still see it until I die\nYou\'re the loss of my life
    //     This happens once every few lifetimes\nThese chemicals hit me like white wine\n\nWhat if I told you I\'m back?\nThe hospital was a drag\nWorst sleep that I ever had\nI circled you on a map\nI haven\'t come around in so long\nBut I\'m coming back so strong\n\nSo when I\nTouch down, call the amateurs and cut \'em from the team\nDitch the clowns, get the crown, baby, I\'m the one to beat\n\'Cause the sign on your heart said it\'s still reserved for me\nHonestly, who are we to fight the alchemy?\n\nHey, you\nWhat if I told you we\'re cool?\nThat child\'s play back in school is forgiven under my rule\nI haven\'t come around in so long\nBut I\'m making a comeback to where I belong\n\nSo when I\nTouch down, call the amateurs and cut \'em from the team\nDitch the clowns, get the crown, baby, I\'m the one to beat\n\'Cause the sign on your heart said it\'s still reserved for me\nHonestly, who are we to fight the alchemy?\n\nThese blokes warm the benches, we been on a winning streak\nHe jokes that it\'s heroin but this time with an \"E\"\n\'Cause the sign on your heart said it\'s still reserved for me\nHonestly, who are we to fight the alchemy?\n\nShirts off, and your friends lift you up over their heads\nBeer sticking to the floor, cheers chanted \'cause they said\nThere was no chance, tryna be the greatest in the league\nWhere\'s the trophy?\nHe just comes running over to me\n\nTouch down, call the amateurs and cut \'em from the team\nDitch the clowns, get the crown, baby, I\'m the one to beat\n\'Cause the sign on your heart said it\'s still reserved for me\nHonestly, who are we to fight the alchemy?\n\nThese blokes warm the benches, we been on a winning streak\nHe jokes that it\'s heroin but this time with an \"E\"\n\'Cause the sign on your heart said it\'s still reserved for me\nHonestly, who are we to fight the alchemy?\n\nThis happens once every few lifetimes\nThese chemicals hit me like white wine
    //     Was any of it true?\nGazing at me starry-eyed\nIn your Jehovah\'s Witness suit\nWho the fuck was that guy?\nYou tried to buy some pills\nFrom a friend of friends of mine\nThey just ghosted you\nNow you know what it feels like\n\nAnd I don\'t even want you back, I just want to know\nIf rusting my sparkling summer was the goal\nAnd I don\'t miss what we had, but could someone give\nA message to the smallest man who ever lived?\n\nYou hung me on your wall\nStabbed me with your push pins\nIn public, showed me off\nThen sank in stoned oblivion\n\'Cause once your queen had come\nYou\'d treat her like an also-ran\nYou didn\'t measure up\nIn any measure of a man\n\nAnd I don\'t even want you back, I just want to know\nIf rusting my sparkling summer was the goal\nAnd I don\'t miss what we had, but could someone give\nA message to the smallest man who ever lived?\n\nWere you sent by someone\nWho wanted me dead?\nDid you sleep with a gun underneath our bed?\nWere you writing a book?\nWere you a sleeper cell spy?\nIn fifty years will all this be declassified?\nAnd you\'ll confess why you did it\nAnd I\'ll say, \"Good riddance\"\n\'Cause it wasn\'t sexy once it wasn\'t forbidden\nI would\'ve died for your sins\nInstead I just died inside\nAnd you deserve prison, but you won\'t get time\nYou\'ll slide into inboxes and slip through the bars\nYou crashed my party and your rental car\nYou said normal girls were \"boring\"\nBut you were gone by the morning\nYou kicked out the stage lights, but you\'re still performing\nAnd in plain sight you hid\nBut you are what you did\nAnd I\'ll forget you, but I\'ll never forgive\nThe smallest man who ever lived
    // ".as_bytes().iter().map(|&x| x as usize).collect();

    let target: Vec<usize> = " Wow This Is Amazing".as_bytes().iter().map(|&x| x as usize).collect();
    let prev_result: Vec<usize> = target;
    println!("original ===> {:?}", prev_result.len());
    for i in 0..iterations {
        let tokens = parser.parse(&prev_result);
        let parsed_tokens = parser.replace(&prev_result, &tokens);
        dbg!(&tokens);
        println!("{i}__iter ===>  {:?}", parsed_tokens.len());
        let values: Vec<&String> = parser.merges.values().collect();
        let hash_set: HashSet<&String> = values.into_iter().collect();
        let unique_values_vec: Vec<String> = hash_set.into_iter().map(|x| x.to_string()).collect();

        println!("{:?}", parser.encode("I'm In Love With You", unique_values_vec));
        // dbg!(hash_set);
        // prev_result = parsed_tokens;
    }
}
